### PR TITLE
Fix/thrift localization empty state and enhance product card 

### LINKED ISSUE #349: Enhance product card
Image
Enhance product card and it's placeholder 
replace it with better image

### PR DESCRIPTION
**Pull request by MuhammedWael9991**
## Description
This PR introduces refactoring the empty state in the thrift screen and enhance some components.
## What Changed
- add localization for no order in the thrift screen.
- add empty section when there is no order in the thrift screen.
- change placeholder for product card.
- rename trending product models and update related logic for consistency.
- add DTO for product summary.
- update default image path for user profile display.

## Screenshots/Videos (if applicable)
image
image

### CODE REVIEW

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `opened`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

File: apps/customer/lib/domain/entities/product_summary.dart [hunk 1]
```diff
@@ -0,0 +1,39 @@
+class ProductSummary {
+  final String id;
+  final String title;
+  final double price;
+  final String imageUrl;
+  final bool isFavorite;
+  final bool? discount;
+  final String? discountText;
```
Comment (abdulazizacc) [inline apps/customer/lib/domain/entities/product_summary.dart]: why creating this entity class when we an entity callled `Product`

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `created`.

File: apps/customer/lib/data/models/product_summary_model.dart [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    return ProductSummaryModel(
+      id: json['id']?.toString() ?? '',
+      title: json['title']?.toString() ?? '',
+      price: (json['price'] as num?)?.toDouble() ?? 0.0,
+      image: json['image']?.toString() ?? '',
+      isFavorite: json['isFavorite'] as bool? ?? false,
+    );
+  }
+
+  // --- Mapping to UI Model ---
```
Comment (abdulazizacc) [inline apps/customer/lib/data/models/product_summary_model.dart]: Nice job bro, you may delete the comments

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `created`.

**Review by marah222 — APPROVED** [review]

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `submitted`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Review by MohamedOmar989 — APPROVED** [review]

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `submitted`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

**Review by abdo-essam — APPROVED** [review]

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `submitted`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `closed`.
