### PR TITLE
Fix/otp screen

### LINKED ISSUE #408: User can’t delete the otp number
Image

### PR DESCRIPTION
**Pull request by israamohamed107**

### CODE REVIEW

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**


❌ An error occurred while updating PR metrics.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

File: packages/design_system/lib/widgets/cards/sellio_otp_card.dart [hunk 1]
```diff
@@ -60,19 +68,71 @@ class _SellioOTPInputCardState extends State<OTPInputCard> {
...
+          _value = firstDigit;
+          _currentState = SellioOTPInputState.filled;
+        });
+        widget.onChanged?.call(firstDigit);
+
+        // Pass all digits to parent - let parent handle focus
+        widget.onCompleted?.call(digitsOnly);
+
+        _controller.clear();
+      }
```
Comment (abdulazizacc) [inline packages/design_system/lib/widgets/cards/sellio_otp_card.dart:132]: delete the comments plz

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `created`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `opened`.

**Comment by abdulazizacc** [comment]
Please provide description or screenshot for the changes you made

**Review by baraa0abd — COMMENTED** [review]
Image

you fix this issue? 

cause I was working on it so we can use the one you working on and close the issue

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Review by abdulazizacc — APPROVED** [review]

**Review by Arzo-zi — APPROVED** [review]

**Review by abdo-essam — APPROVED** [review]
