### PR TITLE
fix: prevent invalid input in full name field

### LINKED ISSUE #426: Full Name textfield
- textfield shouldnt accept blanck (space)  and trem the spaces at the bigging and end
- textfield shouldnt accept anything other than charecters (it is okey to have spaces in the middle)

### PR DESCRIPTION
**Pull request by israamohamed107**

### CODE REVIEW

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `opened`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

File: apps/customer/lib/core/utils/full_name_input_formatter.dart [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  TextEditingValue formatEditUpdate(
+    TextEditingValue oldValue,
+    TextEditingValue newValue,
+  ) {
+    if (newValue.text.startsWith(' ')) return oldValue;
+
+    if (newValue.text.contains('  ')) return oldValue;
+
+    if (newValue.text.length > maxLength) return oldValue;
+    if (!RegExp('^$_allowedPattern*\$').hasMatch(newValue.text)) {
```
Comment (abdo-essam) [inline apps/customer/lib/core/utils/full_name_input_formatter.dart]: Regex is re-created on every keystroke
You can pre-compile regex for best performance like 
```
  static final RegExp _allowedPattern = RegExp(r'^[a-zA-Z\u0600-\u06FF ]*$');
  static final RegExp _doubleSpacePattern = RegExp(r'  ');
```

Usage 
```
    final text = newValue.text;

    if (text.startsWith(' ')) return oldValue;
    if (_doubleSpacePattern.hasMatch(text)) return oldValue;
    if (text.length > maxLength) return oldValue;
    if (!_allowedPattern.hasMatch(text)) return oldValue;
```

**Review by abdulazizacc — APPROVED** [review]

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `submitted`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Review by abdo-essam — APPROVED** [review]
