### PR TITLE
fix: order history direction localization

### LINKED ISSUE #334: order history direction localization
Image

### PR DESCRIPTION
**Pull request by Arzo-zi**
Screenshot 2026-01-28 at 6 47 14 pm
Screenshot 2026-01-28 at 6 47 31 pm

### CODE REVIEW

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `opened`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

File: apps/customer/lib/presentation/screens/order_history/order_history_tabs.dart [hunk 1]
```diff
@@ -20,25 +20,32 @@ class OrderHistoryTabs extends StatelessWidget {
           child: SingleChildScrollView(
             scrollDirection: Axis.horizontal,
             padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
-            child: Row(
-              children: List.generate(
-                state.tabs.length,
-                    (index) {
-                  final isSelected = state.selectedTabIndex == index;
+            child: Directionality(
```
Comment (NadeenRR) [inline apps/customer/lib/presentation/screens/order_history/order_history_tabs.dart]: Why use Directionality? And we still use Localization in the app

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `created`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `synchronize`.

File: apps/customer/lib/presentation/screens/order_history/order_history_tabs.dart (hunk 1 above)
Comment (Arzo-zi) [reply apps/customer/lib/presentation/screens/order_history/order_history_tabs.dart]: i remove it

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `created`.

**Comment by ghost** [comment]
**[Sellio Bot] Auto-update Status**


✅ Branch successfully updated from `develop`.

**Review by marah222 — APPROVED** [review]

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `submitted`.

**Review by MuhammedWael9991 — APPROVED** [review]

**Review by MohamedOmar989 — APPROVED** [review]

**Review by abdo-essam — APPROVED** [review]

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `submitted`.

**Comment by ghost** [comment]
**[Sellio Bot] Metrics Update Status**

📊 PR metrics successfully updated for event: `closed`.
